services:
#    application.example:
#        class: ApplicationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    administration.admin.user:
        class: AdministrationBundle\Admin\UserAdmin
        arguments: [~, AdministrationBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
